---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nodejs-app-1.0
  namespace: default
  labels:
    app: nodejs-app-1.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-app-1.0
  template:
    metadata:
      labels:
        app: nodejs-app-1.0
    spec:
      containers:
      - name: nodejs-app
        image: "abhilashnarayan/nodejs-app-1.0"
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-1.0
  namespace: default
spec:
  selector:
    app: nodejs-app-1.0
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 3000
    port: 80
